### ISSUE TITLE
Some things I noticed

### ISSUE THREAD

**Issue by EddieMattos** [iso4free/spedit#10]
Although the editor is improving every day there are some things that make the user experience a bit difficult.
Things I noticed:
-Selecting the color with the right mouse button or control + click would greatly speed up the artist's work.
- The 'Save sprite project' menu currently does nothing. I was only able to save by clicking on the preview window.
- When I click on new frame the canvas is cleared. Is this the correct behavior?
- Floating windows are not linked to SPEdit, as they stay in the foreground even if I change windows.
- In the 'View / Tool Panels' menu, the boxes appear checked or unchecked, regardless of the visibility of the windows.
- I'm loving the app so far.

These are just a few observations. There is no urgency in implementation.

**Comment by iso4free** [comment]
Yes, many functions do not work because they are not written.
The sprite project format will be implemented after I add multi-frame work and the ability to create animations.
Currently, you can only save a drawing by clicking in the preview window.
With the floating windows, I'm also planning to change something, as I myself don't like the way they work now. Maybe just make separate panels of instumen in the main window or a docking system of these windows with the drawing window?
All other failures and bugs of the program are fixed as they are detected and have free time, because SPEdit is a free and open project, so I can allocate not as much time to work on it as I would like.

**Comment by EddieMattos** [comment]
That's fine, take your time. 
Actually I was trying to create some icons in the app and I came across these difficulties -the color selection was the biggest one.
As for the dockable windows I think it's a good idea.
In fact, my interest in the app was the possibility of a clean design screen, where there was the possibility of disabling some tool windows in favor of space. But this is personal preference.

Thanks!

**Comment by iso4free** [comment]
How do you think it will be most convenient to choose a color for drawing? I will try to implement it as soon as possible.
